FROM node:alpine
COPY . /app
WORKDIR /app
CMD node app.js







# docker build -t hello-docker .
# docker run hello-docker

#docker init


#port binding
#docker run -d -p 9000:80 nginx:1.23
# -d detach -p publish - t terminal

#docker logs container

#docker containers
# docker ps
# docker ps -a  list of all containers running or stopped

# docker start container:version or container id
# docker stop container:version or container id

#docker run --name name_container img_name:version
#docker rmi image_name.

#docker login
#docker login -u username